language: swift
xcode_workspace: Travis.xcworkspace
xcode_scheme: Travis
osx_image: xcode9.3beta
before_install:
  - pod repo update
script:
  # - cd Examples
  # - xcodebuild -version
  # - xcodebuild -project DynamicColorExample.xcodeproj -scheme iOSTests -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 6" -configuration Release ONLY_ACTIVE_ARCH=YES -enableCodeCoverage YES test
  # - bash <(curl -s https://codecov.io/bash) -cF ios

  - xcodebuild -workspace Travis.xcworkspace -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.3' -scheme Travis -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO -derivedDataPath build -enableCodeCoverage YES GCC_GENERATE_TEST_COVERAGE_FILES=YES build test | xcpretty -c
after_success:
  - ls -la
  - bash <(curl -s https://codecov.io/bash) -X xcodeplist -cF ios