# language: swift
# xcode_workspace: Travis.xcworkspace
# xcode_scheme: Travis
# osx_image: xcode9.3
# before_install:
#   - pod repo update
# script:
#   # - cd Examples
#   # - xcodebuild -version
#   # - xcodebuild -project DynamicColorExample.xcodeproj -scheme iOSTests -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 6" -configuration Release ONLY_ACTIVE_ARCH=YES -enableCodeCoverage YES test
#   # - bash <(curl -s https://codecov.io/bash) -cF ios

#   - xcodebuild -workspace Travis.xcworkspace -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.3' -scheme Travis -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO -derivedDataPath build -enableCodeCoverage YES GCC_GENERATE_TEST_COVERAGE_FILES=YES build test | xcpretty -c
# after_success:
#   - ls -la
#   - bash <(curl -s https://codecov.io/bash) -X xcodeplist -cF ios


language: swift
osx_image: xcode9.3
before_install: true
install: true
xcode_project: Travis.xcodeproj
env:
  global:
    - XCODE_PROJECT_NAME=Travis
    - XCODE_SDK=iphonesimulator
    - XCODE_ACTION='build test'
    - XCODE_DESTINATION='platform=iOS Simulator,name=iPhone 8,OS=latest'
    - XCODE_DERIVED_DATA_PATH=build
  matrix:
    - XCODE_SCHEME=Travis
script:
  - set -o pipefail
  - xcodebuild $XCODE_ACTION -project "$TRAVIS_XCODE_PROJECT" -scheme "$XCODE_SCHEME" -sdk "$XCODE_SDK" -destination "$XCODE_DESTINATION" -derivedDataPath "$XCODE_DERIVED_DATA_PATH" | xcpretty
after_success:
  - bash <(curl -s https://codecov.io/bash) -D $XCODE_DERIVED_DATA_PATH -J "^$XCODE_SCHEME$"
notifications:
  email: false
